language: python
python:
 - "3.5"
 - "3.6"

install:
 - pip install -r requirements.txt

services:
 - postgresql

script:
 - ./check_script.py
 - ./check_db.sh
 - python -m pytest

notifications:
 email: false
